[package]
name = "sorotte-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sorotte-secret = { path = "../sorotte-secret" }
thiserror.workspace = true
