[package]
name = "syncplay-compat"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
trace-capture = []

[dependencies]
serde_json.workspace = true
syncplay-protocol = { path = "../syncplay-protocol" }
syncplay-server = { path = "../syncplay-server" }
thiserror.workspace = true

[dev-dependencies]
rustls.workspace = true
rustls-pemfile.workspace = true
syncplay-client-core = { path = "../syncplay-client-core" }
