[package]
name = "sorotte-player-mpv"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
sorotte-player-api = { path = "../sorotte-player-api" }
sorotte-secret = { path = "../sorotte-secret" }

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
sorotte-client-core = { path = "../sorotte-client-core" }
