use super::*;
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;
use std::sync::atomic::AtomicU64;

use crate::{MediaExtractionSettings, MediaMatchToolPaths, fingerprint_media_file_cancellable};

const FIXTURE_TEST: &str = "extraction::process::tests::media_tool_process_fixture";
const FIXTURE_MODE: &str = "SOROTTE_MEDIA_PROCESS_FIXTURE";
const FIXTURE_MARKER: &str = "SOROTTE_MEDIA_PROCESS_MARKER";
const FIXTURE_WATCHDOG: Duration = Duration::from_secs(12);

struct FixtureRoot(PathBuf);

impl FixtureRoot {
    fn new() -> Self {
        static NONCE: AtomicU64 = AtomicU64::new(0);
        let path = std::env::temp_dir().join(format!(
            "sorotte-media-process-{}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos(),
            NONCE.fetch_add(1, Ordering::Relaxed),
        ));
        fs::create_dir(&path).unwrap();
        Self(path)
    }

    fn marker(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }

    fn command(&self, mode: &str, marker: &str) -> Command {
        let mut command = Command::new(std::env::current_exe().unwrap());
        command
            .args([
                "--exact",
                FIXTURE_TEST,
                "--ignored",
                "--nocapture",
                "--test-threads=1",
            ])
            .env(FIXTURE_MODE, mode)
            .env(FIXTURE_MARKER, self.marker(marker));
        command
    }

    fn start(&self, mode: &str, handshake: &str) -> StartedTool {
        let started_at = Instant::now();
        let (child, stdout, stderr) =
            OwnedTool::spawn("ffprobe", &mut self.command(mode, "launched"), || Ok(())).unwrap();
        let started = StartedTool {
            child,
            stdout,
            stderr,
            started_at,
        };
        wait_for_marker(&self.marker(handshake));
        started
    }

    fn tools(&self, probe_mode: &str, audio_mode: &str) -> MediaMatchToolPaths {
        MediaMatchToolPaths {
            ffprobe: self.wrapper("ffprobe", probe_mode),
            ffmpeg: self.wrapper("ffmpeg", audio_mode),
        }
    }

    fn wrapper(&self, name: &str, mode: &str) -> PathBuf {
        let executable = std::env::current_exe().unwrap();
        let marker = self.marker(name);
        #[cfg(windows)]
        {
            let path = self.0.join(format!("{name}.cmd"));
            // Paths are generated by this fixture; quoting also exercises a real
            // Command .cmd launch without interpreting incoming media arguments.
            let script = format!(
                "@echo off\r\nset \"{FIXTURE_MODE}={mode}\"\r\nset \"{FIXTURE_MARKER}={}\"\r\n\"{}\" --exact {FIXTURE_TEST} --ignored --nocapture --test-threads=1\r\n",
                marker.display(),
                executable.display(),
            );
            fs::write(&path, script).unwrap();
            path
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let quote =
                |value: &Path| format!("'{}'", value.to_string_lossy().replace('\'', "'\\''"));
            // Keep the executable separate from its after-launch marker on
            // Unix too; an existing wrapper must not satisfy the handshake.
            let path = self.0.join(format!("{name}.sh"));
            let script = format!(
                "#!/bin/sh\n{FIXTURE_MODE}='{mode}' {FIXTURE_MARKER}={} exec {} --exact {FIXTURE_TEST} --ignored --nocapture --test-threads=1\n",
                quote(&marker),
                quote(&executable),
            );
            fs::write(&path, script).unwrap();
            fs::set_permissions(&path, fs::Permissions::from_mode(0o700)).unwrap();
            path
        }
    }

    fn media(&self) -> PathBuf {
        let path = self.0.join("fixture media.mkv");
        fs::write(&path, b"synthetic metadata fixture").unwrap();
        path
    }
}

impl Drop for FixtureRoot {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.0).expect("fixture process must release all files before return");
    }
}

fn wait_for_marker(path: &Path) -> (u32, u64) {
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        if let Ok(text) = fs::read_to_string(path)
            && let Some((pid, birth)) = text.split_once(':')
            && let (Ok(pid), Ok(birth)) = (pid.parse(), birth.parse())
        {
            return (pid, birth);
        }
        assert!(
            Instant::now() < deadline,
            "fixture handshake missing: {}",
            path.display()
        );
        thread::sleep(Duration::from_millis(5));
    }
}

#[cfg(windows)]
fn process_birth(pid: u32) -> Option<u64> {
    use std::os::windows::io::{AsRawHandle, FromRawHandle, OwnedHandle};
    use windows_sys::Win32::Foundation::FILETIME;
    use windows_sys::Win32::System::Threading::{
        GetProcessTimes, OpenProcess, PROCESS_QUERY_LIMITED_INFORMATION,
    };
    // SAFETY: access is restricted to querying the fixture PID's creation time.
    let handle = unsafe { OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, 0, pid) };
    if handle.is_null() {
        return None;
    }
    // SAFETY: OpenProcess returned a new owned handle.
    let process = unsafe { OwnedHandle::from_raw_handle(handle) };
    let mut creation = FILETIME::default();
    let mut exit = FILETIME::default();
    let mut kernel = FILETIME::default();
    let mut user = FILETIME::default();
    // SAFETY: the handle is live and all time buffers are distinct and writable.
    if unsafe {
        GetProcessTimes(
            process.as_raw_handle(),
            &mut creation,
            &mut exit,
            &mut kernel,
            &mut user,
        )
    } == 0
    {
        return None;
    }
    Some((u64::from(creation.dwHighDateTime) << 32) | u64::from(creation.dwLowDateTime))
}

#[cfg(unix)]
fn process_birth(pid: u32) -> Option<u64> {
    #[cfg(target_os = "linux")]
    {
        fs::read_to_string(format!("/proc/{pid}/stat"))
            .ok()?
            .rsplit_once(") ")?
            .1
            .split_whitespace()
            .nth(19)?
            .parse()
            .ok()
    }
    #[cfg(not(target_os = "linux"))]
    {
        Some(0)
    }
}

#[cfg(windows)]
fn process_is_running(pid: u32, birth: u64) -> bool {
    use std::os::windows::io::{AsRawHandle, FromRawHandle, OwnedHandle};
    use windows_sys::Win32::Foundation::WAIT_TIMEOUT;
    use windows_sys::Win32::System::Threading::{
        OpenProcess, PROCESS_SYNCHRONIZE, WaitForSingleObject,
    };
    // Bind the handle lifetime before checking creation identity; PID reuse after
    // successful fixture exit must not mistake a different process for a survivor.
    // SAFETY: access is restricted to querying the fixture PID's exit signal.
    let handle = unsafe { OpenProcess(PROCESS_SYNCHRONIZE, 0, pid) };
    if handle.is_null() {
        return false;
    }
    // SAFETY: OpenProcess returned a new owned handle.
    let process = unsafe { OwnedHandle::from_raw_handle(handle) };
    if process_birth(pid) != Some(birth) {
        return false;
    }
    // SAFETY: the process handle is live and a zero timeout never waits.
    unsafe { WaitForSingleObject(process.as_raw_handle(), 0) == WAIT_TIMEOUT }
}

#[cfg(unix)]
fn process_is_running(pid: u32, birth: u64) -> bool {
    if process_birth(pid) != Some(birth) {
        return false;
    }
    #[cfg(target_os = "linux")]
    {
        // Descendants are reparented on group termination; an init-owned zombie
        // is already terminated even when PID 1 has not reaped it yet.
        if let Ok(status) = fs::read_to_string(format!("/proc/{pid}/stat"))
            && status
                .rsplit_once(") ")
                .is_some_and(|(_, rest)| rest.starts_with('Z'))
        {
            return false;
        }
    }
    // SAFETY: signal zero only queries the liveness of this fixture process.
    unsafe { libc::kill(pid as libc::pid_t, 0) == 0 }
}

fn assert_stopped(marker: &Path) {
    let (pid, birth) = wait_for_marker(marker);
    assert!(
        !process_is_running(pid, birth),
        "owned fixture PID {pid} survived operation completion: {}",
        marker.display()
    );
}

fn cancel_after_handshake(marker: PathBuf, flag: Arc<AtomicBool>) -> thread::JoinHandle<Instant> {
    thread::spawn(move || {
        wait_for_marker(&marker);
        let cancelled_at = Instant::now();
        flag.store(true, Ordering::Release);
        cancelled_at
    })
}

#[test]
#[ignore = "subprocess fixture entry point; invoked explicitly by process contract tests"]
fn media_tool_process_fixture() {
    let Ok(mode) = std::env::var(FIXTURE_MODE) else {
        return;
    };
    let marker = PathBuf::from(std::env::var_os(FIXTURE_MARKER).unwrap());
    let identity = format!(
        "{}:{}",
        std::process::id(),
        process_birth(std::process::id()).unwrap()
    );
    fs::write(&marker, &identity).unwrap();
    match mode.as_str() {
        "silent" => thread::sleep(FIXTURE_WATCHDOG),
        "duration" => {
            println!("\n120\n");
            std::process::exit(0);
        }
        "delay" => {
            thread::sleep(Duration::from_millis(700));
            println!("\n42\n");
            std::process::exit(0);
        }
        "long-delay" => {
            thread::sleep(Duration::from_millis(2500));
            std::process::exit(0);
        }
        "stdout" | "stderr" => {
            let mut output: Box<dyn Write> = if mode == "stdout" {
                Box::new(std::io::stdout().lock())
            } else {
                Box::new(std::io::stderr().lock())
            };
            let until = Instant::now() + FIXTURE_WATCHDOG;
            while Instant::now() < until {
                if output.write_all(&[b'x'; 32 * 1024]).is_err() {
                    break;
                }
            }
        }
        "error-tail" => {
            let mut stderr = std::io::stderr().lock();
            stderr.write_all(&vec![b'a'; 96 * 1024]).unwrap();
            stderr.write_all(b"\nuseful final diagnostic\n").unwrap();
            stderr.flush().unwrap();
            std::process::exit(7);
        }
        "descendant" | "closed-pipe-descendant" => {
            let descendant_marker = marker.with_extension("descendant");
            let mut command = Command::new(std::env::current_exe().unwrap());
            command
                .args([
                    "--exact",
                    FIXTURE_TEST,
                    "--ignored",
                    "--nocapture",
                    "--test-threads=1",
                ])
                .env(FIXTURE_MODE, "silent")
                .env(FIXTURE_MARKER, &descendant_marker)
                .stdin(Stdio::null());
            if mode == "closed-pipe-descendant" {
                #[cfg(windows)]
                prevent_extra_standard_handle_inheritance();
                command.stdout(Stdio::null()).stderr(Stdio::null());
            } else {
                command.stdout(Stdio::inherit()).stderr(Stdio::inherit());
            }
            let _descendant = command.spawn().unwrap();
            wait_for_marker(&descendant_marker);
            fs::write(marker.with_extension("parent-exit"), &identity).unwrap();
            std::process::exit(0);
        }
        other => panic!("unknown fixture mode: {other}"),
    }
    std::process::exit(81);
}

#[cfg(windows)]
fn prevent_extra_standard_handle_inheritance() {
    use windows_sys::Win32::Foundation::{HANDLE_FLAG_INHERIT, SetHandleInformation};
    use windows_sys::Win32::System::Console::{GetStdHandle, STD_ERROR_HANDLE, STD_OUTPUT_HANDLE};
    for stream in [STD_OUTPUT_HANDLE, STD_ERROR_HANDLE] {
        // SAFETY: only this subprocess fixture's own standard pipe handles are
        // affected; disabling inheritance does not close the parent's handles.
        unsafe {
            assert_ne!(
                SetHandleInformation(GetStdHandle(stream), HANDLE_FLAG_INHERIT, 0),
                0
            );
        }
    }
}

#[test]
fn pre_cancel_starts_no_process_and_precedes_filesystem_work() {
    let root = FixtureRoot::new();
    let cancelled = AtomicBool::new(true);
    let result = run_output(
        "ffprobe",
        root.command("silent", "launched"),
        Some(&cancelled),
        Deadline::after(Duration::from_secs(5)),
        PROBE_STDOUT_LIMIT,
    );
    assert!(matches!(
        result,
        Err(MediaFingerprintError::Cancelled { tool: "ffprobe" })
    ));
    assert!(!root.marker("launched").exists());
    let tools = root.tools("silent", "silent");
    let result = fingerprint_media_file_cancellable(
        root.marker("missing media"),
        &tools,
        &MediaExtractionSettings::default(),
        &cancelled,
    );
    assert!(matches!(
        result,
        Err(MediaFingerprintError::Cancelled { tool: "ffprobe" })
    ));
    assert!(!root.marker("ffprobe").exists());
    assert!(!root.marker("ffmpeg").exists());
}

#[test]
fn cancellation_after_probe_launch_prevents_audio_and_returns_no_fingerprint() {
    let root = FixtureRoot::new();
    let tools = root.tools("silent", "duration");
    let cancelled = Arc::new(AtomicBool::new(false));
    let controller = cancel_after_handshake(root.marker("ffprobe"), Arc::clone(&cancelled));
    let result = fingerprint_media_file_cancellable(
        root.media(),
        &tools,
        &MediaExtractionSettings::default(),
        &cancelled,
    );
    let cancelled_at = controller.join().unwrap();
    assert!(
        matches!(
            result,
            Err(MediaFingerprintError::Cancelled { tool: "ffprobe" })
        ),
        "{result:?}"
    );
    assert!(cancelled_at.elapsed() < Duration::from_secs(2));
    assert_stopped(&root.marker("ffprobe"));
    assert!(!root.marker("ffmpeg").exists());
}

#[test]
fn cancellation_after_audio_launch_is_not_a_degraded_fingerprint() {
    let root = FixtureRoot::new();
    let tools = root.tools("duration", "silent");
    let cancelled = Arc::new(AtomicBool::new(false));
    let controller = cancel_after_handshake(root.marker("ffmpeg"), Arc::clone(&cancelled));
    let result = fingerprint_media_file_cancellable(
        root.media(),
        &tools,
        &MediaExtractionSettings::default(),
        &cancelled,
    );
    let cancelled_at = controller.join().unwrap();
    assert!(
        matches!(
            result,
            Err(MediaFingerprintError::Cancelled { tool: "ffmpeg" })
        ),
        "{result:?}"
    );
    assert!(cancelled_at.elapsed() < Duration::from_secs(2));
    assert_stopped(&root.marker("ffprobe"));
    assert_stopped(&root.marker("ffmpeg"));
}

#[test]
fn successful_probe_convenience_api_preserves_duration_parsing() {
    let root = FixtureRoot::new();
    let tools = root.tools("duration", "silent");
    assert_eq!(
        crate::probe_media_duration_seconds(&tools.ffprobe, root.media()).unwrap(),
        Some(120.0)
    );
    assert_stopped(&root.marker("ffprobe"));
}

#[test]
fn endless_stdout_and_stderr_are_bounded_and_reaped() {
    for mode in ["stdout", "stderr"] {
        let root = FixtureRoot::new();
        let result = run_output(
            "ffprobe",
            root.command(mode, "launched"),
            None,
            Deadline::after(Duration::from_secs(5)),
            PROBE_STDOUT_LIMIT,
        );
        let error = result.unwrap_err().to_string();
        assert!(error.contains(&format!("{mode} exceeded its")), "{error}");
        assert!(error.len() < STDERR_TAIL_LIMIT + 512);
        assert_stopped(&root.marker("launched"));
    }
}

#[test]
fn pcm_output_limit_is_derived_from_the_requested_window() {
    let root = FixtureRoot::new();
    let tools = root.tools("duration", "stdout");
    let cancelled = AtomicBool::new(false);
    let result = fingerprint_media_file_cancellable(
        root.media(),
        &tools,
        &MediaExtractionSettings::default(),
        &cancelled,
    );
    let error = result.unwrap_err().to_string();
    assert!(
        error.contains("stdout exceeded its 320000-byte limit"),
        "{error}"
    );
    assert_stopped(&root.marker("ffmpeg"));
}

#[test]
fn diagnostic_tail_preserves_the_end_without_retaining_all_stderr() {
    let root = FixtureRoot::new();
    let (output, _) = run_output(
        "ffprobe",
        root.command("error-tail", "launched"),
        None,
        Deadline::after(Duration::from_secs(5)),
        PROBE_STDOUT_LIMIT,
    )
    .unwrap();
    assert_eq!(output.status.code(), Some(7));
    assert_eq!(output.stderr.len(), STDERR_TAIL_LIMIT);
    assert!(output.stderr.ends_with(b"useful final diagnostic\n"));
    assert_stopped(&root.marker("launched"));
}

#[test]
fn silent_process_obeys_deadline_and_is_reaped() {
    let root = FixtureRoot::new();
    let process = root.start("silent", "launched");
    let started = Instant::now();
    let result = run_started(
        "ffprobe",
        process,
        None,
        Deadline::after(Duration::from_secs(1)),
        PROBE_STDOUT_LIMIT,
        |_| Ok(()),
    );
    assert!(
        matches!(
            result,
            Err(MediaFingerprintError::TimedOut {
                tool: "ffprobe",
                ..
            })
        ),
        "{result:?}"
    );
    assert!(started.elapsed() < Duration::from_secs(3));
    assert_stopped(&root.marker("launched"));
}

#[test]
fn a_shared_operation_deadline_is_not_renewed_by_the_next_tool() {
    let root = FixtureRoot::new();
    let deadline = Deadline::after(Duration::from_secs(3));
    let started = Instant::now();
    run_output(
        "ffprobe",
        root.command("delay", "first"),
        None,
        deadline,
        PROBE_STDOUT_LIMIT,
    )
    .unwrap();
    let result = run_output(
        "ffmpeg",
        root.command("long-delay", "second"),
        None,
        deadline,
        PROBE_STDOUT_LIMIT,
    );
    assert!(
        matches!(
            result,
            Err(MediaFingerprintError::TimedOut { tool: "ffmpeg", .. })
        ),
        "{result:?}"
    );
    assert!(started.elapsed() < Duration::from_secs(5));
    assert_stopped(&root.marker("first"));
    assert_stopped(&root.marker("second"));
}

#[test]
fn exited_child_with_inherited_pipe_descendant_obeys_drain_deadline() {
    let root = FixtureRoot::new();
    let process = root.start("descendant", "launched.parent-exit");
    let started = Instant::now();
    let result = run_started(
        "ffprobe",
        process,
        None,
        Deadline::after(Duration::from_secs(2)),
        PROBE_STDOUT_LIMIT,
        |_| Ok(()),
    );
    assert!(
        matches!(
            result,
            Err(MediaFingerprintError::TimedOut {
                tool: "ffprobe",
                ..
            })
        ),
        "{result:?}"
    );
    assert!(started.elapsed() < Duration::from_secs(4));
    assert!(
        root.marker("launched.parent-exit").exists(),
        "parent must exit while descendant holds the pipes"
    );
    assert_stopped(&root.marker("launched"));
    assert_stopped(&root.marker("launched.descendant"));
}

#[test]
fn cancellation_reaps_descendant_that_holds_an_exited_childs_pipes() {
    let root = FixtureRoot::new();
    let cancelled = Arc::new(AtomicBool::new(false));
    let controller =
        cancel_after_handshake(root.marker("launched.parent-exit"), Arc::clone(&cancelled));
    let result = run_output(
        "ffprobe",
        root.command("descendant", "launched"),
        Some(&cancelled),
        Deadline::after(Duration::from_secs(6)),
        PROBE_STDOUT_LIMIT,
    );
    let cancelled_at = controller.join().unwrap();
    assert!(
        matches!(
            result,
            Err(MediaFingerprintError::Cancelled { tool: "ffprobe" })
        ),
        "{result:?}"
    );
    assert!(cancelled_at.elapsed() < Duration::from_secs(2));
    assert_stopped(&root.marker("launched"));
    assert_stopped(&root.marker("launched.descendant"));
}

#[test]
fn successful_child_cannot_leave_a_descendant_with_closed_pipes_running() {
    let root = FixtureRoot::new();
    run_output(
        "ffprobe",
        root.command("closed-pipe-descendant", "launched"),
        None,
        Deadline::after(Duration::from_secs(5)),
        PROBE_STDOUT_LIMIT,
    )
    .unwrap();
    assert_stopped(&root.marker("launched"));
    assert_stopped(&root.marker("launched.descendant"));
}

#[test]
fn cancellation_while_consuming_output_cannot_return_a_successful_result() {
    let root = FixtureRoot::new();
    let cancelled = AtomicBool::new(false);
    let result = run_streaming(
        "ffprobe",
        root.command("duration", "launched"),
        Some(&cancelled),
        Deadline::after(Duration::from_secs(5)),
        PROBE_STDOUT_LIMIT,
        |_| {
            cancelled.store(true, Ordering::Release);
            Ok(())
        },
    );
    assert!(
        matches!(result, Err(MediaFingerprintError::Cancelled { .. })),
        "{result:?}"
    );
    // libtest can emit its banner before entering the fixture; the parent still
    // reaps the process even if the marker has not yet been created.
    if root.marker("launched").exists() {
        assert_stopped(&root.marker("launched"));
    }
}
