[package]
name = "sorotte-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
sorotte-client-core = { path = "../sorotte-client-core" }
sorotte-core = { path = "../sorotte-core" }
sorotte-player-api = { path = "../sorotte-player-api" }

[dev-dependencies]
sorotte-player-mpv = { path = "../sorotte-player-mpv" }
