use super::*;

#[derive(Debug)]
pub struct ClientSession {
    pub username: Option<String>,
    pub room: Option<String>,
    pub domain: SyncDomain,
    server_readiness_supported: Option<bool>,
    server_set_others_readiness_supported: Option<bool>,
    server_managed_rooms_supported: Option<bool>,
    server_shared_playlists_supported: Option<bool>,
    server_chat_supported: Option<bool>,
    server_persistent_rooms_supported: Option<bool>,
    server_max_username_length: Option<usize>,
    server_max_room_name_length: Option<usize>,
    server_max_filename_length: Option<usize>,
    desync_config: DesyncCorrectionConfig,
    reconnect_policy: ReconnectPolicyConfig,
    behavior_config: SessionBehaviorConfig,
    readiness_autoplay_config: ReadinessAutoplayConfig,
    chat_config: ChatConfig,
    speed_changed: bool,
    pub(crate) behind_first_detected_at_seconds: Option<f64>,
    last_paused_on_leave_at_seconds: Option<f64>,
    last_advanced_at_seconds: Option<f64>,
    last_rewound_at_seconds: Option<f64>,
    user_views: BTreeMap<String, ClientUserView>,
    known_rooms: BTreeSet<String>,
    room_playlists: BTreeMap<String, RoomPlaylistView>,
    room_playstates: BTreeMap<String, RoomPlaystateView>,
    room_playstate_updated_at_seconds: BTreeMap<String, f64>,
    pending_playlist: Option<RoomPlaylistView>,
    playlist_active_targets_before_index_update: BTreeMap<String, String>,
    reconnect_ready_restore_snapshot: Option<bool>,
    reconnect_ready_restore_intent: Option<bool>,
    reconnect_file_restore_snapshot: Option<Value>,
    reconnect_file_restore_intent: Option<Value>,
    reconnect_controller_restore_snapshot: Option<bool>,
    reconnect_playlist_restore_snapshot: Option<ReconnectPlaylistRestoreIntent>,
    reconnect_playlist_restore_intent: Option<ReconnectPlaylistRestoreIntent>,
    pub(crate) reconnect_state_restore_validation_pending: bool,
    reconnect_state_restore_validation_retry_attempts: u32,
    reconnect_state_restore_validation_retry_cooldown_ticks: u32,
    reconnect_state_restore_validation_mismatch_notified: bool,
    reconnect_state_restore_validation_mismatch_seen_in_cycle: bool,
    reconnect_state_restore_correction_consecutive_mismatch_cycles: u32,
    reconnect_state_restore_correction_consecutive_retry_exhaustions: u32,
    reconnect_state_restore_correction_recovery_cooldown_reconnect_cycles_remaining: u32,
    reconnect_state_restore_correction_recovery_suppressed_this_cycle: bool,
    reconnect_state_restore_correction_recovery_reenable_notification_pending: bool,
    reconnect_state_restore_correction_recovery_reenabled_this_cycle: bool,
    pub(crate) reconnect_state_restore_correction_metrics: ReconnectStateRestoreCorrectionMetrics,
    pending_chat_notifications: Vec<ChatNotification>,
    pending_controlled_room_creation_notifications: Vec<ControlledRoomCreationNotification>,
    pending_controller_auth_notifications: Vec<ControllerAuthTransitionNotification>,
    pending_user_change_notifications: Vec<UserChangeNotification>,
    reconnect_in_progress: bool,
    reconnect_connected_intent: bool,
    controlled_room_switch_intent: Option<String>,
    pending_local_room_switch_target: Option<String>,
    controller_reidentify_intent: Option<(String, String)>,
    last_controller_auth_password_attempt: Option<String>,
    controlled_room_passwords: BTreeMap<String, String>,
    playlist_undo_snapshots: BTreeMap<String, Vec<String>>,
    playlist_shuffle_nonce: u64,
    received_first_playlist_index: bool,
    pending_playlist_index_reset_pause_before_sync: Option<bool>,
    pending_playlist_index_reset_refresh_recently_advanced: bool,
    suppress_next_self_playlist_index_reset: bool,
    last_seek_position_before_manual_seek: Option<f64>,
    pub(crate) local_position: Option<f64>,
    pub(crate) local_paused: Option<bool>,
    pub(crate) local_paused_for_cache: Option<bool>,
    pub(crate) local_cache_buffering_percent: Option<f64>,
    pub(crate) pending_cache_room_playstate_resync: bool,
    autoplay_enabled: bool,
    autoplay_timer_running: bool,
    autoplay_time_left_seconds: f64,
    client_ignoring_on_the_fly: u32,
    server_ignoring_on_the_fly: u32,
}

#[derive(Debug, Clone)]
pub(crate) struct ClientSessionLocalActionSnapshot {
    user_views: BTreeMap<String, ClientUserView>,
    local_position: Option<f64>,
    local_paused: Option<bool>,
    local_paused_for_cache: Option<bool>,
    local_cache_buffering_percent: Option<f64>,
    pending_cache_room_playstate_resync: bool,
    last_seek_position_before_manual_seek: Option<f64>,
    last_paused_on_leave_at_seconds: Option<f64>,
    last_rewound_at_seconds: Option<f64>,
    autoplay_timer_running: bool,
    autoplay_time_left_seconds: f64,
}

impl Default for ClientSession {
    fn default() -> Self {
        let readiness_autoplay_config = ReadinessAutoplayConfig::default();
        let autoplay_time_left_seconds = readiness_autoplay_config.autoplay_delay_seconds;

        Self {
            username: None,
            room: None,
            domain: SyncDomain::default(),
            server_readiness_supported: None,
            server_set_others_readiness_supported: None,
            server_managed_rooms_supported: None,
            server_shared_playlists_supported: None,
            server_chat_supported: None,
            server_persistent_rooms_supported: None,
            server_max_username_length: None,
            server_max_room_name_length: None,
            server_max_filename_length: None,
            desync_config: DesyncCorrectionConfig::default(),
            reconnect_policy: ReconnectPolicyConfig::default(),
            behavior_config: SessionBehaviorConfig::default(),
            readiness_autoplay_config,
            chat_config: ChatConfig::default(),
            speed_changed: false,
            behind_first_detected_at_seconds: None,
            last_paused_on_leave_at_seconds: None,
            last_advanced_at_seconds: None,
            last_rewound_at_seconds: None,
            user_views: BTreeMap::new(),
            known_rooms: BTreeSet::new(),
            room_playlists: BTreeMap::new(),
            room_playstates: BTreeMap::new(),
            room_playstate_updated_at_seconds: BTreeMap::new(),
            pending_playlist: None,
            playlist_active_targets_before_index_update: BTreeMap::new(),
            reconnect_ready_restore_snapshot: None,
            reconnect_ready_restore_intent: None,
            reconnect_file_restore_snapshot: None,
            reconnect_file_restore_intent: None,
            reconnect_controller_restore_snapshot: None,
            reconnect_playlist_restore_snapshot: None,
            reconnect_playlist_restore_intent: None,
            reconnect_state_restore_validation_pending: false,
            reconnect_state_restore_validation_retry_attempts: 0,
            reconnect_state_restore_validation_retry_cooldown_ticks: 0,
            reconnect_state_restore_validation_mismatch_notified: false,
            reconnect_state_restore_validation_mismatch_seen_in_cycle: false,
            reconnect_state_restore_correction_consecutive_mismatch_cycles: 0,
            reconnect_state_restore_correction_consecutive_retry_exhaustions: 0,
            reconnect_state_restore_correction_recovery_cooldown_reconnect_cycles_remaining: 0,
            reconnect_state_restore_correction_recovery_suppressed_this_cycle: false,
            reconnect_state_restore_correction_recovery_reenable_notification_pending: false,
            reconnect_state_restore_correction_recovery_reenabled_this_cycle: false,
            reconnect_state_restore_correction_metrics:
                ReconnectStateRestoreCorrectionMetrics::default(),
            pending_chat_notifications: Vec::new(),
            pending_controlled_room_creation_notifications: Vec::new(),
            pending_controller_auth_notifications: Vec::new(),
            pending_user_change_notifications: Vec::new(),
            reconnect_in_progress: false,
            reconnect_connected_intent: false,
            controlled_room_switch_intent: None,
            pending_local_room_switch_target: None,
            controller_reidentify_intent: None,
            last_controller_auth_password_attempt: None,
            controlled_room_passwords: BTreeMap::new(),
            playlist_undo_snapshots: BTreeMap::new(),
            playlist_shuffle_nonce: 0,
            received_first_playlist_index: false,
            pending_playlist_index_reset_pause_before_sync: None,
            pending_playlist_index_reset_refresh_recently_advanced: false,
            suppress_next_self_playlist_index_reset: false,
            last_seek_position_before_manual_seek: None,
            local_position: None,
            local_paused: None,
            local_paused_for_cache: None,
            local_cache_buffering_percent: None,
            pending_cache_room_playstate_resync: false,
            autoplay_enabled: false,
            autoplay_timer_running: false,
            autoplay_time_left_seconds,
            client_ignoring_on_the_fly: 0,
            server_ignoring_on_the_fly: 0,
        }
    }
}

mod apply;
mod file_metadata;
mod helpers;
mod lifecycle;
mod playback;
mod playlist;
mod queries;
mod reconnect;

#[cfg(test)]
#[allow(clippy::field_reassign_with_default)]
mod tests;
