[package]
name = "syncplay-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
rustls.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["io-util", "net"] }
tokio-rustls.workspace = true
syncplay-client-app = { path = "../syncplay-client-app" }
syncplay-client-core = { path = "../syncplay-client-core" }
syncplay-player-mpv = { path = "../syncplay-player-mpv" }
syncplay-player-api = { path = "../syncplay-player-api" }
syncplay-plex = { path = "../syncplay-plex" }
syncplay-protocol = { path = "../syncplay-protocol" }
syncplay-server = { path = "../syncplay-server" }
webpki-roots.workspace = true
