[package]
name = "sorotte-client-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
sorotte-client-core = { path = "../sorotte-client-core" }
sorotte-secret = { path = "../sorotte-secret" }
