[package]
name = "sorotte-media-match"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rustfft.workspace = true
rusqlite.workspace = true
windows-sys.workspace = true
